// <auto-generated />
using Hotel_Carina.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Hotel_Carina.Migrations
{
    [DbContext(typeof(DataBaseContext))]
    [Migration("20210513105041_updatedDbSeedData")]
    partial class updatedDbSeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Hotel_Carina.Data.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ShortName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Nigeria",
                            ShortName = "NGN"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ghana",
                            ShortName = "GHN"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Aberden",
                            ShortName = "ABD"
                        });
                });

            modelBuilder.Entity("Hotel_Carina.Data.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsBooked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCanceled")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsBooked = true,
                            IsCanceled = false,
                            Name = "King Judge"
                        },
                        new
                        {
                            Id = 2,
                            IsBooked = true,
                            IsCanceled = false,
                            Name = "King Nothighame"
                        },
                        new
                        {
                            Id = 3,
                            IsBooked = true,
                            IsCanceled = true,
                            Name = "Bob Neil"
                        });
                });

            modelBuilder.Entity("Hotel_Carina.Data.CustomerHotel", b =>
                {
                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<int>("HotelId")
                        .HasColumnType("int");

                    b.HasKey("CustomerId", "HotelId");

                    b.HasIndex("HotelId");

                    b.ToTable("CustomerHotels");

                    b.HasData(
                        new
                        {
                            CustomerId = 1,
                            HotelId = 1
                        },
                        new
                        {
                            CustomerId = 1,
                            HotelId = 2
                        },
                        new
                        {
                            CustomerId = 2,
                            HotelId = 3
                        });
                });

            modelBuilder.Entity("Hotel_Carina.Data.Hotel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<double>("Ratings")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Ketu Lagos",
                            CountryId = 1,
                            Name = "Five Fouth by Sheraton",
                            Price = 1503m,
                            Ratings = 3.5
                        },
                        new
                        {
                            Id = 2,
                            Address = "Lekki Lagos",
                            CountryId = 1,
                            Name = "Protea Hotel",
                            Price = 432.10m,
                            Ratings = 5.0
                        },
                        new
                        {
                            Id = 3,
                            Address = "Ogudu Lagos",
                            CountryId = 2,
                            Name = "Sheraton Hills and Towers",
                            Price = 780.33m,
                            Ratings = 4.5
                        },
                        new
                        {
                            Id = 4,
                            Address = "Abuja Qrt",
                            CountryId = 2,
                            Name = "Choice Gate Towers",
                            Price = 580.13m,
                            Ratings = 3.5
                        },
                        new
                        {
                            Id = 5,
                            Address = "Mandela Prims street Uganda ",
                            CountryId = 3,
                            Name = "New Horizon Towers",
                            Price = 780.33m,
                            Ratings = 4.5
                        },
                        new
                        {
                            Id = 6,
                            Address = "Havilah Close Austria ",
                            CountryId = 3,
                            Name = "Susan Wesly Hotel",
                            Price = 220.33m,
                            Ratings = 1.5
                        },
                        new
                        {
                            Id = 7,
                            Address = "Khinshasha Kenya street",
                            CountryId = 2,
                            Name = "Zanzibar Towers & Suits",
                            Price = 180.33m,
                            Ratings = 4.5
                        },
                        new
                        {
                            Id = 8,
                            Address = "Jburg South Africa",
                            CountryId = 3,
                            Name = "BurgeKhalif Hotel & Suits",
                            Price = 80.33m,
                            Ratings = 4.5
                        });
                });

            modelBuilder.Entity("Hotel_Carina.Data.CustomerHotel", b =>
                {
                    b.HasOne("Hotel_Carina.Data.Customer", "Customer")
                        .WithMany("CustomerHotels")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hotel_Carina.Data.Hotel", "Hotel")
                        .WithMany("CustomerHotels")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("Hotel_Carina.Data.Hotel", b =>
                {
                    b.HasOne("Hotel_Carina.Data.Country", "Country")
                        .WithMany("Hotels")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Hotel_Carina.Data.Country", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("Hotel_Carina.Data.Customer", b =>
                {
                    b.Navigation("CustomerHotels");
                });

            modelBuilder.Entity("Hotel_Carina.Data.Hotel", b =>
                {
                    b.Navigation("CustomerHotels");
                });
#pragma warning restore 612, 618
        }
    }
}
